name: build-master
description: compiles and tests master branch on change

on:
  push:
    branches:
      - master

jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
      - name: build
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      run: go version
      run: go clean
      run: go test ./...